name: example
description: Example app for animated_vector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_vector: ^0.2.3
  animated_vector_annotations: ^0.3.0

  flutter:
    sdk: flutter

dev_dependencies:
  animated_vector_gen: ^0.3.1
  build_runner: ^2.16.1
  flutter_test:
    sdk: flutter

  lint: ^2.14.0

flutter:
  uses-material-design: true
