name: animated_vector_gen
description: Code generator for animated_vector. Allows to generate vector data from shape shifter files
version: 0.3.1
license: MIT
homepage: https://github.com/HrX03/animated_vector/tree/main/packages/animated_vector_annotations
repository: https://github.com/HrX03/animated_vector

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^13.3.0
  animated_vector_annotations: ^0.3.0
  build: ^4.0.11
  code_builder: ^4.12.0
  dart_style: ^3.1.13
  glob: ^2.2.0
  source_gen: ^4.2.0
